services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - shared-app-network
  #   restart: unless-stopped

  db:
    image: mysql:8
    container_name: mysql_poc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PassWord123
      MYSQL_DATABASE: poc
    command: ["--port=3307"]
    ports:
      - "3307:3307"
    volumes:
      - apexcise_db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - shared-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3307", "-uroot", "-pPassWord123"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_poc
    restart: always
    environment:
      QDRANT__SERVICE__HTTP_PORT: 7333
      QDRANT__SERVICE__GRPC_PORT: 7334
    ports:
      - "7400:7333"
      - "7401:7334"
    volumes:
      - apexcise_qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "true"]
    networks:
      - shared-app-network

  apexcisebackend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: apexcise_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: PassWord123
      DB_NAME: poc
    ports:
      - "5002:5002"
    volumes:
      - ./src:/app/src  
    networks:
      - shared-app-network

  apexciseuserquery:
    build:
      context: .
      dockerfile: userbackend.Dockerfile
    container_name: apexcise_userquery
    restart: always
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: PassWord123
      DB_NAME: poc
      QDRANT_URL: http://qdrant:7333
      QDRANT_API_KEY: ""
    ports:
      - "5005:5005"
    volumes:
      - ./userbackend:/app/userbackend
      - ./uploads:/app/uploads
    networks:
      - shared-app-network
  # prophet:
  #   build:
  #     context: .
  #     dockerfile: prophet.Dockerfile
  #   container_name: prophet
  #   restart: always
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - shared-app-network
  
volumes:
  apexcise_db_data:
  apexcise_qdrant_data:

networks:
  shared-app-network:
    external: true
